version: '3.8'
services:
  hrm-system:
    image: your-registry/hrmsystem:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./hsqldb_data:/app/.jmix/hsqldb
    environment:
      - SPRING_PROFILES_ACTIVE=production